[package]
name = "fckn-gay-email"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[features]
default = ["dummy", "lettre"]
dummy = ["dep:fckn-gay-email-dummy"]
lettre = ["dep:fckn-gay-email-lettre"]

[dependencies]
fckn-gay-email-dummy = { path = "./implementors/dummy", optional = true }
fckn-gay-email-interface = { path = "./interface" }
fckn-gay-email-lettre = { path = "./implementors/lettre", optional = true }

serde.workspace = true

[dev-dependencies]
toml.workspace = true
