[package]
name = "fckn-gay-email"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
fckn-gay-email-dummy = { path = "./implementors/dummy" }
fckn-gay-email-interface = { path = "./interface" }
fckn-gay-email-lettre = { path = "./implementors/lettre" }

serde.workspace = true
