[package]
name = "fckn-gay-dns-porkbun"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
fckn-gay-dns-interface = { path = "../../interface" }
fckn-gay-secret = { workspace = true }

porkbun-api = { workspace = true, features = ["default-client", "tracing"] }
serde.workspace = true
