[package]
name = "fckn-gay-email-dummy"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
fckn-gay-email-interface = { path = "../../interface" }

lettre = { workspace = true, features = [
  "aws-lc-rs",
  "builder",
  "hostname",
  "pool",
  "rustls-platform-verifier",
  "smtp-transport",
  "tokio1",
  "tokio1-rustls",
] }
serde.workspace = true
