[package]
name = "fckn-gay-user-database-hardcoded"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
fckn-gay-user-database-interface = { path = "../../interface" }

chrono.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync"] }
uuid.workspace = true
