[package]
name = "fckn-gay-user-database-diesel"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
diesel.workspace = true
fckn-gay-user-database-interface = { path = "../../interface" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }

#forces bundled sqlite to be used, making it easier to build everywhere
libsqlite3-sys = { version = "0.33", features = ["bundled"] }
