[package]
name = "fckn-gay-user-database"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[features]
default = ["csv", "diesel", "dummy"]
csv = ["dep:fckn-gay-user-database-csv"]
diesel = ["dep:fckn-gay-user-database-diesel"]
dummy = ["dep:fckn-gay-user-database-dummy"]

[dependencies]
fckn-gay-user-database-csv = { path = "./implementors/csv", optional = true }
fckn-gay-user-database-diesel = { path = "./implementors/diesel", optional = true }
fckn-gay-user-database-dummy = { path = "./implementors/dummy", optional = true }
fckn-gay-user-database-interface = { path = "./interface" }

serde.workspace = true

[dev-dependencies]
toml.workspace = true
