[package]
name = "fckn-gay-dns-hickory"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fckn-gay-dns-interface = { path = "../../interface" }

async-trait = { workspace = true }
hickory-server = { workspace = true }
libsqlite3-sys = { version = "0.33", features = ["bundled"] }
serde.workspace = true
tokio = { workspace = true, features = ["sync"] }
